export type ChainKey = "bsc" | "base";

// What the backend sends (JSON body of the HTTP trigger)
export type Evidence = {
  incidentId: `0x${string}`; // bytes32, generated by backend (keccak of chain+txHash)
  chain: ChainKey;
  vault: `0x${string}`;
  suspectTxHash: `0x${string}`;
  attacker: `0x${string}`;
  features: {
    walletAgeSeconds: number | null; // age of attacker EOA at the test call; null when unknown
    mixerFunded: boolean; // first funds came from a known mixer
    reentrancyDetected: boolean; // same vault function entered twice in one trace
    vaultBalanceDeltaBps: number; // simulated loss as basis points of vault balance (3800 = 38%)
    flashLoanEntry: boolean;
    newContractTarget: boolean; // call came from a contract deployed < 1h ago
  };
};

export type Config = {
  pauseThreshold: number; // 80
  authorizedEVMAddress: string; // backend signer address (HTTP trigger auth)
  requireAuth: boolean; // false allows trigger({}) for local simulation
  gasLimit: string; // e.g. "500000"
  chains: Record<ChainKey, { chainSelectorName: string; guardian: `0x${string}` | null }>;
};
